#!/bin/bash
#
# /etc/init.d/logstash-shipper -- startup script for LogStash shipper.
#
# Fork of elasticsearch init script for logstash by Joe McDonagh <jmcdonagh@thesilentpenguin.com>
# Written by Miquel van Smoorenburg <miquels@cistron.nl>.
# Modified for Debian GNU/Linux  by Ian Murdock <imurdock@gnu.ai.mit.edu>.
# Modified for Tomcat by Stefan Gybas <sgybas@debian.org>.
# Modified for Tomcat6 by Thierry Carrez <thierry.carrez@ubuntu.com>.
# Additional improvements by Jason Brittain <jason.brittain@mulesoft.com>.
# Modified by Nicolas Huray for logstash-shipper <nicolas.huray@gmail.com>.
#
### BEGIN INIT INFO
# Provides:          logstash-shipper
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts logstash-shipper
# Description:       Starts logstash-shipper using start-stop-daemon
### END INIT INFO

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=logstash-shipper
DESC="Logstash Shipper Agent"
DEFAULT=/etc/default/$NAME

if [ `id -u` -ne 0 ]; then
   echo "You need root privileges to run this script"
   exit 1
fi

. /lib/lsb/init-functions

if [ -r /etc/default/rcS ]; then
   . /etc/default/rcS
fi

# The following variables can be overwritten in $DEFAULT

# Run logstash-shipper as this user ID and group ID
LS_USER=logstash
LS_GROUP=logstash

# The first existing directory is used for JAVA_HOME (if JAVA_HOME is not defined in $DEFAULT)
JDK_DIRS="/usr/lib/jvm/java-7-oracle /usr/lib/jvm/java-6-sun /usr/lib/jvm/java-7-openjdk /usr/lib/jvm/java-6-openjdk"

# Look for the right JVM to use
for jdir in $JDK_DIRS; do
   if [ -r "$jdir/bin/java" -a -z "${JAVA_HOME}" ]; then
      JAVA_HOME="$jdir"
   fi
done

export JAVA_HOME

# Directory where the logstash all in one jar lives
LS_HOME=/usr/share/logstash

# Additional Java OPTS
#LS_JAVA_OPTS=

# logstash-shipper log directory
LOG_DIR=/var/log/logstash

# logstash-shipper configuration directory
CONF_DIR=/etc/logstash

# logstash-shipper configuration file
CONF_FILE=$CONF_DIR/shipper.cfg

# logstash-shipper log file
LOG_FILE=$LOG_DIR/shipper.log

# End of variables that can be overwritten in $DEFAULT

# overwrite settings from default file
if [ -f "$DEFAULT" ]; then
   . "$DEFAULT"
fi

# Define other required variables
PID_FILE=/var/run/$NAME.pid
DAEMON=$LS_HOME/logstash.jar
DAEMON_OPTS="agent -f ${CONF_FILE} --log ${LOG_FILE}"

export LS_MIN_MEM LS_MAX_MEM

# Check DAEMON exists
if ! test -e $DAEMON; then
   log_failure_msg "Daemon $DAEMON doesn't exist"
   exit 1
fi

case "$1" in
   start)
      if [ -z "$JAVA_HOME" ]; then
         log_failure_msg "no JDK found - please set JAVA_HOME"
         exit 1
      fi

      log_daemon_msg "Starting $DESC"
   
      if start-stop-daemon --test --start --pidfile "$PID_FILE" \
         --user "$LS_USER" --exec "$JAVA_HOME/bin/java" \
      >/dev/null; then
         # Prepare environment
         mkdir -p "$LOG_DIR" && chown "$LS_USER":"$LS_GROUP" "$LOG_DIR"
         touch "$PID_FILE" && chown "$LS_USER":"$LS_GROUP" "$PID_FILE"
         ulimit -n 65535

         # Start Daemon
         start-stop-daemon --start -b --user "$LS_USER" -c "$LS_USER":"$LS_USER" -d "$LS_HOME" --pidfile "$PID_FILE" --make-pidfile --exec "$JAVA_HOME/bin/java" -- $LS_JAVA_OPTS -jar $DAEMON $DAEMON_OPTS

         sleep 1

         if start-stop-daemon --test --start --pidfile "$PID_FILE" \
            --user "$LS_USER" --exec "$JAVA_HOME/bin/java" \
         >/dev/null; then

            if [ -f "$PID_FILE" ]; then
               rm -f "$PID_FILE"
            fi

            log_end_msg 1
         else
            log_end_msg 0
         fi
      else
         log_progress_msg "(already running)"
         log_end_msg 0
      fi
   ;;    
   stop)
      log_daemon_msg "Stopping $DESC"

      set +e

      if [ -f "$PID_FILE" ]; then 
         start-stop-daemon --stop --pidfile "$PID_FILE" \
            --user "$LS_USER" \
            --retry=TERM/20/KILL/5 >/dev/null

         if [ $? -eq 1 ]; then
            log_progress_msg "$DESC is not running but pid file exists, cleaning up"
         elif [ $? -eq 3 ]; then
            PID="`cat $PID_FILE`"
            log_failure_msg "Failed to stop $DESC (pid $PID)"
            exit 1
         fi

         rm -f "$PID_FILE"
      else
         log_progress_msg "(not running)"
      fi

      log_end_msg 0
      set -e
   ;;
   status)
      set +e

      start-stop-daemon --test --start --pidfile "$PID_FILE" \
         --user "$LS_USER" --exec "$JAVA_HOME/bin/java" \
      >/dev/null 2>&1

      if [ "$?" = "0" ]; then
         if [ -f "$PID_FILE" ]; then
            log_success_msg "$DESC is not running, but pid file exists."
            exit 1
         else
            log_success_msg "$DESC is not running."
            exit 3
         fi
      else
         log_success_msg "$DESC is running with pid `cat $PID_FILE`"
      fi

      set -e
   ;;
   restart|force-reload)
      if [ -f "$PID_FILE" ]; then
         $0 stop
         sleep 1
      fi

      $0 start
   ;;
   *)
      log_success_msg "Usage: $0 {start|stop|restart|force-reload|status}"
      exit 1
   ;;
esac

exit 0

